WIP: [Fixes #183] GeoNode User Guide
GeoNode/documentation pull request #191
Opened 2021-11-19 16:45 UTC by marthamareal

2022-01-10 11:49 UTC, giohappy requested changes
@marthamareal regarding permissions, it would be good to have an explanation of what the different grants (View, Download, Edit, Manager) offer for each type of resource.

2022-01-14 10:49 UTC, marthamareal commented
updated PR with the changes

2022-01-14 10:53 UTC, gannebamm commented on usage/managing_datasets/dataset_permissions.rst
> +Share OPtions
typo `Options`

2022-02-10 19:11 UTC, fernandinand approved these changes
LGTM. Just confirm if thumbnail image needs update

2022-02-14 09:58 UTC, marthamareal commented on usage/managing_documents/document_editing.rst
>  .. figure:: img/document_uploading_thumbnail.png
@fernandinand I used a black background image, do you suggest using another visible image?
![doc](https://user-images.githubusercontent.com/20810749/153841980-77b70e97-743f-463e-8ab9-8609ba22e241.png)

2022-02-17 17:50 UTC, fernandinand commented on usage/managing_documents/document_editing.rst
>  .. figure:: img/document_uploading_thumbnail.png
@marthamareal Apologies, I thought this was an error on image upload/screenshot. Although is not the best image we can leave it for now.

2022-02-18 11:46 UTC, giohappy commented on usage/managing_documents/document_editing.rst
>  .. figure:: img/document_uploading_thumbnail.png
@marthamareal @fernandinand I guess it won't take much recreating a better screenshot,..

2022-02-23 10:40 UTC, merged